
    {
      url: "https://upload.wikimedia.org/wikipedia/pt/c/c0/Death_Note_vol._01.jpg",
      nome: "Death Note",
    },
    {
      url: "https://upload.wikimedia.org/wikipedia/pt/6/65/Tokyo_Ghoul_volume_1.jpg",
      nome: "Tokyo Ghoul",
    },
    {
      url: "https://images-na.ssl-images-amazon.com/images/I/51suPR+LhgS._SX349_BO1,204,203,200_.jpg",
      nome: "No Game No Life",
    },
    {
      url: "https://upload.wikimedia.org/wikipedia/pt/b/b2/SwordArtOnlineVol.1.jpg",
      nome: "Sword Art Online",
    },
  ];

  const arrayAnimesMaisAssistidos = [
    {
      url: "https://img1.ak.crunchyroll.com/i/spire4/5568ffb263f6bcba85a639980b80dd9a1612993223_full.jpg",

      nome: "Naruto Shipudden",
    },
    {
      url: "https://upload.wikimedia.org/wikipedia/pt/thumb/5/51/Shingeki_no_Kyojin_1%C2%AA_temporada.jpg/230px-Shingeki_no_Kyojin_1%C2%AA_temporada.jpg",
      nome: "Shingeki No Kyojin",
    },
    {
      url: "https://jovemnerd.com.br/wp-content/uploads/2019/05/black-clover-poster.jpg",
      nome: "Black Clover",
    },
    {
      url: "https://upload.wikimedia.org/wikipedia/pt/7/74/Dragon_Ball_Super_Key_visual.jpg",
      nome: "Dragon Ball Super",
    },

    {
      url: "https://media.fstatic.com/FOmZuVltaHfgiLZdvFkhpGTX5kE=/290x478/smart/media/movies/covers/2021/03/defghgbf.jpg",

      nome: "Boruto – Naruto Next Generation",
    },

    {
      url: "https://wikiimg.tojsiabtv.com/wikipedia/en/thumb/6/62/Main_characters_of_One_Piece.png/250px-Main_characters_of_One_Piece.png",

      nome: "One Piece",
    },
    {
      url: "https://upload.wikimedia.org/wikipedia/pt/5/5a/Boku_no_Hero_Academia_Volume_1.png",

      nome: "Boku No Hero",
    },

    {
      url: "https://m.media-amazon.com/images/I/51dONmpss4L.jpg",

      nome: "JoJo’s Bizarre Adventure",
    },
  ];
